In [1]:
# 1. Import Library
import yaml
import os
import sys

from pathlib import Path

In [2]:
# 2. Import Function
sys.path.append(os.path.abspath("../.."))

from src.data_collection import (
    fetch_tickers_data,
    fetch_index_data
)

In [3]:
# 3. Load Parameter
with open("../../config/parameter.yaml", "r") as f:
    parameter_config = yaml.safe_load(f)

stocks_parameter = parameter_config["stocks_parameter"]
data_parameter = parameter_config["data_parameter"]

idx_80 = stocks_parameter["idx_80"]
lq_45 = stocks_parameter["lq_45"]
idx_30 = stocks_parameter["idx_30"]
index = stocks_parameter["index"]

interval = data_parameter["interval"]
start_date = data_parameter["start_date"]
end_date = data_parameter["end_date"]

tickers = sorted(set(idx_80 + lq_45 + idx_30))

print(f"Total saham : {len(tickers)}")
print(f"Total index : {len(index)}")
print(f"Interval    : {interval}")
print(f"Periode     : {start_date} to {end_date}")

Total saham : 80
Total index : 3
Interval    : 1d
Periode     : 2026-01-01 to 2027-01-01

In [4]:
# 4. Retrieve Data
df_all_data, success_tickers = fetch_tickers_data(tickers, start_date, end_date, interval)

df_all_data_index = fetch_index_data(index, start_date, end_date, interval)

[1/80] Downloading AADI.JK ...
[2/80] Downloading ACES.JK ...
[3/80] Downloading ADMR.JK ...
[4/80] Downloading ADRO.JK ...
[5/80] Downloading AKRA.JK ...
[6/80] Downloading AMMN.JK ...
[7/80] Downloading AMRT.JK ...
[8/80] Downloading ANTM.JK ...
[9/80] Downloading ARTO.JK ...
[10/80] Downloading ASII.JK ...
[11/80] Downloading AUTO.JK ...
[12/80] Downloading AVIA.JK ...
[13/80] Downloading BBCA.JK ...
[14/80] Downloading BBNI.JK ...
[15/80] Downloading BBRI.JK ...
[16/80] Downloading BBTN.JK ...
[17/80] Downloading BFIN.JK ...
[18/80] Downloading BMRI.JK ...
[19/80] Downloading BNGA.JK ...
[20/80] Downloading BRIS.JK ...
[21/80] Downloading BRMS.JK ...
[22/80] Downloading BRPT.JK ...
[23/80] Downloading BSDE.JK ...
[24/80] Downloading BTPS.JK ...
[25/80] Downloading BUKA.JK ...
[26/80] Downloading CMRY.JK ...
[27/80] Downloading CPIN.JK ...
[28/80] Downloading CTRA.JK ...
[29/80] Downloading DSNG.JK ...
[30/80] Downloading ELSA.JK ...
[31/80] Downloading EMTK.JK ...
[32/80] Downloading ENRG.JK ...
[33/80] Downloading ERAA.JK ...
[34/80] Downloading ESSA.JK ...
[35/80] Downloading EXCL.JK ...
[36/80] Downloading GOTO.JK ...
[37/80] Downloading HEAL.JK ...
[38/80] Downloading HRUM.JK ...
[39/80] Downloading ICBP.JK ...
[40/80] Downloading INCO.JK ...
[41/80] Downloading INDF.JK ...
[42/80] Downloading INDY.JK ...
[43/80] Downloading INKP.JK ...
[44/80] Downloading INTP.JK ...
[45/80] Downloading ISAT.JK ...
[46/80] Downloading ITMG.JK ...
[47/80] Downloading JPFA.JK ...
[48/80] Downloading JSMR.JK ...
[49/80] Downloading KLBF.JK ...
[50/80] Downloading LSIP.JK ...
[51/80] Downloading MAPA.JK ...
[52/80] Downloading MAPI.JK ...
[53/80] Downloading MBMA.JK ...
[54/80] Downloading MDKA.JK ...
[55/80] Downloading MEDC.JK ...
[56/80] Downloading MIKA.JK ...
[57/80] Downloading MNCN.JK ...
[58/80] Downloading MTEL.JK ...
[59/80] Downloading MYOR.JK ...
[60/80] Downloading NCKL.JK ...
[61/80] Downloading PANI.JK ...
[62/80] Downloading PGAS.JK ...
[63/80] Downloading PGEO.JK ...
[64/80] Downloading PNLF.JK ...
[65/80] Downloading PTBA.JK ...
[66/80] Downloading PTRO.JK ...
[67/80] Downloading PWON.JK ...
[68/80] Downloading RAJA.JK ...
[69/80] Downloading SCMA.JK ...
[70/80] Downloading SIDO.JK ...
[71/80] Downloading SMGR.JK ...
[72/80] Downloading SMRA.JK ...
[73/80] Downloading SRTG.JK ...
[74/80] Downloading SSIA.JK ...
[75/80] Downloading TAPG.JK ...
[76/80] Downloading TKIM.JK ...
[77/80] Downloading TLKM.JK ...
[78/80] Downloading TOWR.JK ...
[79/80] Downloading UNTR.JK ...
[80/80] Downloading UNVR.JK ...
[1/3] Downloading ^JKSE ...
[2/3] Downloading GC=F ...
[3/3] Downloading ^JKLQ45 ...

In [5]:
# 5. Export to CSV
with open("../../config/paths.yaml", "r") as f:
    paths_config = yaml.safe_load(f)

raw_data_path = Path(paths_config["data"]["01_raw"])
raw_data_path.mkdir(parents=True, exist_ok=True)

output_file = raw_data_path / "raw_technicals.csv"
output_file_index = raw_data_path / "raw_technicals_index.csv"

df_all_data.to_csv(output_file, index=False)
df_all_data_index.to_csv(output_file_index, index=False)

print(f"Data saham berhasil disimpan ke : '{output_file}'")
print(f"Data index berhasil disimpan ke : '{output_file_index}'")
print(f"Total saham yang terunduh       : {len(success_tickers)}")
print(f"Total baris data saham          : {len(df_all_data):,}")
print(f"Total baris data index          : {len(df_all_data_index):,}")

Data saham berhasil disimpan ke : '..\..\data\01_raw\raw_technicals.csv'
Data index berhasil disimpan ke : '..\..\data\01_raw\raw_technicals_index.csv'
Total saham yang terunduh       : 80
Total baris data saham          : 3,520
Total baris data index          : 133

In [6]:
df_all_data.head(9999999)

,ticker,date,open,high,low,close,adj_close,volume
0,AADI.JK,2026-01-02,7000.0,7050.0,6975.0,7050.0,7050.0,4330300.0
1,AADI.JK,2026-01-05,7075.0,7150.0,7000.0,7025.0,7025.0,9948600.0
2,AADI.JK,2026-01-06,7100.0,7150.0,6975.0,7075.0,7075.0,12032400.0
3,AADI.JK,2026-01-07,7100.0,7400.0,7100.0,7350.0,7350.0,18963000.0
4,AADI.JK,2026-01-08,7425.0,7550.0,7250.0,7400.0,7400.0,22058600.0
...,...,...,...,...,...,...,...,...
3515,UNVR.JK,2026-03-03,2260.0,2280.0,2080.0,2080.0,2080.0,29682000.0
3516,UNVR.JK,2026-03-04,2090.0,2090.0,1920.0,1935.0,1935.0,31919800.0
3517,UNVR.JK,2026-03-05,1975.0,2040.0,1975.0,1990.0,1990.0,14954200.0
3518,UNVR.JK,2026-03-06,1990.0,2040.0,1955.0,1975.0,1975.0,11788500.0
3519,UNVR.JK,2026-03-09,1955.0,1955.0,1845.0,1880.0,1880.0,20756600.0

In [7]:
df_all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3520 entries, 0 to 3519
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ticker     3520 non-null   object
 1   date       3520 non-null   datetime64[ns]
 2   open       3520 non-null   float64
 3   high       3520 non-null   float64
 4   low        3520 non-null   float64
 5   close      3520 non-null   float64
 6   adj_close  3520 non-null   float64
 7   volume     3520 non-null   float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 220.1+ KB

In [8]:
df_all_data_index.head(9999999)

,ticker,date,open,high,low,close,adj_close,volume
0,^JKSE,2026-01-02,8676.74,8748.13,8664.97,8748.13,8748.13,4.718639e+08
1,^JKSE,2026-01-05,8778.73,8859.19,8732.32,8859.19,8859.19,6.657351e+08
2,^JKSE,2026-01-06,8890.72,8940.11,8839.01,8933.61,8933.61,6.304328e+08
3,^JKSE,2026-01-07,8959.09,8970.87,8916.03,8944.81,8944.81,6.554095e+08
4,^JKSE,2026-01-08,8946.70,9002.92,8918.41,8925.47,8925.47,4.893161e+08
...,...,...,...,...,...,...,...,...
128,^JKLQ45,2026-03-03,817.69,823.66,805.60,805.60,805.60,1.062720e+10
129,^JKLQ45,2026-03-04,802.31,802.71,761.27,772.45,772.45,1.771440e+10
130,^JKLQ45,2026-03-05,784.70,792.76,782.27,787.82,787.82,7.392600e+09
131,^JKLQ45,2026-03-06,786.21,786.54,767.95,776.05,776.05,1.038080e+10
132,^JKLQ45,2026-03-09,753.74,757.30,733.53,750.58,750.58,0.000000e+00

In [9]:
df_all_data_index.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ticker     133 non-null    object
 1   date       133 non-null    datetime64[ns]
 2   open       133 non-null    float64
 3   high       133 non-null    float64
 4   low        133 non-null    float64
 5   close      133 non-null    float64
 6   adj_close  133 non-null    float64
 7   volume     133 non-null    float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 8.4+ KB